print("Hello Marc")
require("marc.plugins-setup")
require("marc.core.keymaps")
require("marc.core.colorscheme")
require("marc.core.options")
require("marc.plugins.comment")
require("marc.plugins.nvim-tree")
require("marc.plugins.lualine")
require("marc.plugins.telescope")
require("marc.plugins.nvim-cmp")
require("marc.plugins.lsp.mason")
require("marc.plugins.lsp.lspsaga")
require("marc.plugins.lsp.lspconfig")
require("marc.plugins.lsp.null-ls")
require("marc.plugins.autopairs")
require("marc.plugins.treesitter")
require("marc.plugins.gitsigns")
require("marc.plugins.harpoon")
